CREATE TABLE customer (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  phone_number VARCHAR(15) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  type VARCHAR(20) NOT NULL CHECK (type IN ('User', 'Company')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
