CREATE TABLE payment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  amount DECIMAL(10, 2) NOT NULL,
  payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  orders_id INT NOT NULL,
  FOREIGN KEY (orders_id) REFERENCES orders(id) ON DELETE CASCADE
);
